addCommandAlias("CB",  "project coreBundleCallback")
addCommandAlias("CE",  "project coreBundleCatsEffect")
addCommandAlias("CG",  "project coreGeneric")
addCommandAlias("E",   "project extra")
addCommandAlias("FM",  "project facadeMain")
addCommandAlias("FT",  "project facadeTest")
addCommandAlias("GH",  "project ghpages")
addCommandAlias("M2",  "project extraExtMonocle2")
addCommandAlias("M3",  "project extraExtMonocle3")
addCommandAlias("RR",  "project testReactRefresh")
addCommandAlias("RRJ", "project testReactRefreshJS")
addCommandAlias("TS",  "project tests")
addCommandAlias("TU",  "project testUtil")

addCommandAlias("trrc", "testReactRefreshJS/clean;testReactRefresh/test")
addCommandAlias("trr", "testReactRefresh/test")
addCommandAlias("tt",  "tests/test")
