#!/bin/bash
set -euo pipefail
cd "$(dirname "$0")"
[ $# -ne 1 ] && echo "Usage: $0 <file>" && exit 1

files="$(fgrep /src/ todo-scala3.md | fgrep "$1")"

for f in $files; do
  echo
  echo "Reusing: $f"
  ./mv_src s "$f"
  perl -pi -e 's!'"$f"'\n!!' todo-scala3.md
done
echo
