#!/bin/bash
cd "$(dirname "$0")" || exit 1

s0=scalaz-7.0
s1=scalaz-7.1

f=src/main/scala/japgolly/scalajs/react/ScalazReact.scala
echo "$f"
perl -pe '
  s!(?<=[^A-Z_]M\[)_!+_!;
  s/{Optional => _, _}/_/;
  ' < $s1/$f > $s0/$f
sed -i "
  /Optional\[Maybe/,/^ *} *$/d;
  /^object/a\  // Don't edit this directly. Run $(basename "$0")
" $s0/$f

