package japgolly.scalajs.react.vdom

import japgolly.scalajs.react.ReactElement
import scalatags._
import scalatags.generic.{Namespace, Util}

trait ReactSvgTags extends generic.SvgTags[VDomBuilder, ReactElement, ReactFragT]{
  implicit val svgNamespaceConfig = Namespace.svgNamespaceConfig
  val altglyph = "altglyph".tag[ReactElement]
  val altglyphdef = "altglyphdef".tag[ReactElement]
  val altglyphitem = "altglyphitem".tag[ReactElement]
  val animate = "animate".tag[ReactElement]
  val animatemotion = "animatemotion".tag[ReactElement]
  val animatetransform = "animatetransform".tag[ReactElement]
  val circle = "circle".tag[ReactElement]
  val clippath = "clippath".tag[ReactElement]
  val `color-profile` = "color-profile".tag[ReactElement]
  val cursor = "cursor".tag[ReactElement]
  val defs = "defs".tag[ReactElement]
  val desc = "desc".tag[ReactElement]
  val ellipse = "ellipse".tag[ReactElement]
  val feblend = "feblend".tag[ReactElement]
  val fecolormatrix = "fecolormatrix".tag[ReactElement]
  val fecomponenttransfer = "fecomponenttransfer".tag[ReactElement]
  val fecomposite = "fecomposite".tag[ReactElement]
  val feconvolvematrix = "feconvolvematrix".tag[ReactElement]
  val fediffuselighting = "fediffuselighting".tag[ReactElement]
  val fedisplacementmap = "fedisplacementmap".tag[ReactElement]
  val fedistantlighting = "fedistantlighting".tag[ReactElement]
  val feflood = "feflood".tag[ReactElement]
  val fefunca = "fefunca".tag[ReactElement]
  val fefuncb = "fefuncb".tag[ReactElement]
  val fefuncg = "fefuncg".tag[ReactElement]
  val fefuncr = "fefuncr".tag[ReactElement]
  val fegaussianblur = "fegaussianblur".tag[ReactElement]
  val feimage = "feimage".tag[ReactElement]
  val femerge = "femerge".tag[ReactElement]
  val femergenode = "femergenode".tag[ReactElement]
  val femorphology = "femorphology".tag[ReactElement]
  val feoffset = "feoffset".tag[ReactElement]
  val fepointlight = "fepointlight".tag[ReactElement]
  val fespecularlighting = "fespecularlighting".tag[ReactElement]
  val fespotlight = "fespotlight".tag[ReactElement]
  val fetile = "fetile".tag[ReactElement]
  val feturbulance = "feturbulance".tag[ReactElement]
  val filter = "filter".tag[ReactElement]
  val font = "font".tag[ReactElement]
  val `font-face` = "font-face".tag[ReactElement]
  val `font-face-format` = "font-face-format".tag[ReactElement]
  val `font-face-name` = "font-face-name".tag[ReactElement]
  val `font-face-src` = "font-face-src".tag[ReactElement]
  val `font-face-uri` = "font-face-uri".tag[ReactElement]
  val foreignobject = "foreignobject".tag[ReactElement]
  val g = "g".tag[ReactElement]
  val glyph = "glyph".tag[ReactElement]
  val glyphref = "glyphref".tag[ReactElement]
  val hkern = "hkern".tag[ReactElement]
  val image = "image".tag[ReactElement]
  val line = "line".tag[ReactElement]
  val lineargradient = "lineargradient".tag[ReactElement]
  val marker = "marker".tag[ReactElement]
  val mask = "mask".tag[ReactElement]
  val metadata = "metadata".tag[ReactElement]
  val `missing-glyph` = "missing-glyph".tag[ReactElement]
  val mpath = "mpath".tag[ReactElement]
  val path = "path".tag[ReactElement]
  val pattern = "pattern".tag[ReactElement]
  val polygon = "polygon".tag[ReactElement]
  val polyline = "polyline".tag[ReactElement]
  val radialgradient = "radialgradient".tag[ReactElement]
  val rect = "rect".tag[ReactElement]
  val set = "set".tag[ReactElement]
  val stop = "stop".tag[ReactElement]
  val svg = "svg".tag[ReactElement]
  val switch = "switch".tag[ReactElement]
  val symbol = "symbol".tag[ReactElement]
  val text = "text".tag[ReactElement]
  val textpath = "textpath".tag[ReactElement]
  val tref = "tref".tag[ReactElement]
  val tspan = "tspan".tag[ReactElement]
  val use = "use".tag[ReactElement]
  val view = "view".tag[ReactElement]
  val vkern = "vkern".tag[ReactElement]
}
