package japgolly.scalajs.react.hooks

// DO NOT MANUALLY EDIT
// DO NOT MANUALLY EDIT
//
// THIS IS GENERATED BY RUNNING genHooks IN SBT
//
// DO NOT MANUALLY EDIT
// DO NOT MANUALLY EDIT

import japgolly.scalajs.react.hooks.Hooks.UseCallbackArg
import japgolly.scalajs.react.{Callback, Reusability, Reusable}
import scala.scalajs.js

trait UseCallbackExtraApi[Ctx, Step <: Api.Step] { self: Api.Primary[Ctx, Step] =>
  import Api.UseCallbackInline

  /** Returns a memoized callback.
    *
    * @see https://reactjs.org/docs/hooks-reference.html#usecallback
    */
  @inline final def useCallback1[A](f: (A) => Callback)(implicit step: Step): step.Next[Reusable[(A) => Callback]] =
    useCallback((_: Ctx) => (_: UseCallbackInline)(f))

  /** Returns a memoized callback.
    *
    * Pass an inline callback and dependencies. useCallback will return a memoized version of the callback that only
    * changes if one of the dependencies has changed. This is useful when passing callbacks to optimized child
    * components that rely on reference equality to prevent unnecessary renders.
    *
    * @see https://reactjs.org/docs/hooks-reference.html#usecallback
    */
  @inline final def useCallback1[A, Z](f: (A) => Callback, deps: Z)(implicit r: Reusability[Z], step: Step): step.Next[Reusable[(A) => Callback]] =
    useCallback((_: Ctx) => (_: UseCallbackInline)(f, deps))


  /** Returns a memoized callback.
    *
    * @see https://reactjs.org/docs/hooks-reference.html#usecallback
    */
  @inline final def useCallback2[A, B](f: (A, B) => Callback)(implicit step: Step): step.Next[Reusable[(A, B) => Callback]] =
    useCallback((_: Ctx) => (_: UseCallbackInline)(f))

  /** Returns a memoized callback.
    *
    * Pass an inline callback and dependencies. useCallback will return a memoized version of the callback that only
    * changes if one of the dependencies has changed. This is useful when passing callbacks to optimized child
    * components that rely on reference equality to prevent unnecessary renders.
    *
    * @see https://reactjs.org/docs/hooks-reference.html#usecallback
    */
  @inline final def useCallback2[A, B, Z](f: (A, B) => Callback, deps: Z)(implicit r: Reusability[Z], step: Step): step.Next[Reusable[(A, B) => Callback]] =
    useCallback((_: Ctx) => (_: UseCallbackInline)(f, deps))


  /** Returns a memoized callback.
    *
    * @see https://reactjs.org/docs/hooks-reference.html#usecallback
    */
  @inline final def useCallback3[A, B, C](f: (A, B, C) => Callback)(implicit step: Step): step.Next[Reusable[(A, B, C) => Callback]] =
    useCallback((_: Ctx) => (_: UseCallbackInline)(f))

  /** Returns a memoized callback.
    *
    * Pass an inline callback and dependencies. useCallback will return a memoized version of the callback that only
    * changes if one of the dependencies has changed. This is useful when passing callbacks to optimized child
    * components that rely on reference equality to prevent unnecessary renders.
    *
    * @see https://reactjs.org/docs/hooks-reference.html#usecallback
    */
  @inline final def useCallback3[A, B, C, Z](f: (A, B, C) => Callback, deps: Z)(implicit r: Reusability[Z], step: Step): step.Next[Reusable[(A, B, C) => Callback]] =
    useCallback((_: Ctx) => (_: UseCallbackInline)(f, deps))


  /** Returns a memoized callback.
    *
    * @see https://reactjs.org/docs/hooks-reference.html#usecallback
    */
  @inline final def useCallback4[A, B, C, D](f: (A, B, C, D) => Callback)(implicit step: Step): step.Next[Reusable[(A, B, C, D) => Callback]] =
    useCallback((_: Ctx) => (_: UseCallbackInline)(f))

  /** Returns a memoized callback.
    *
    * Pass an inline callback and dependencies. useCallback will return a memoized version of the callback that only
    * changes if one of the dependencies has changed. This is useful when passing callbacks to optimized child
    * components that rely on reference equality to prevent unnecessary renders.
    *
    * @see https://reactjs.org/docs/hooks-reference.html#usecallback
    */
  @inline final def useCallback4[A, B, C, D, Z](f: (A, B, C, D) => Callback, deps: Z)(implicit r: Reusability[Z], step: Step): step.Next[Reusable[(A, B, C, D) => Callback]] =
    useCallback((_: Ctx) => (_: UseCallbackInline)(f, deps))


  /** Returns a memoized callback.
    *
    * @see https://reactjs.org/docs/hooks-reference.html#usecallback
    */
  @inline final def useCallback5[A, B, C, D, E](f: (A, B, C, D, E) => Callback)(implicit step: Step): step.Next[Reusable[(A, B, C, D, E) => Callback]] =
    useCallback((_: Ctx) => (_: UseCallbackInline)(f))

  /** Returns a memoized callback.
    *
    * Pass an inline callback and dependencies. useCallback will return a memoized version of the callback that only
    * changes if one of the dependencies has changed. This is useful when passing callbacks to optimized child
    * components that rely on reference equality to prevent unnecessary renders.
    *
    * @see https://reactjs.org/docs/hooks-reference.html#usecallback
    */
  @inline final def useCallback5[A, B, C, D, E, Z](f: (A, B, C, D, E) => Callback, deps: Z)(implicit r: Reusability[Z], step: Step): step.Next[Reusable[(A, B, C, D, E) => Callback]] =
    useCallback((_: Ctx) => (_: UseCallbackInline)(f, deps))


  /** Returns a memoized callback.
    *
    * @see https://reactjs.org/docs/hooks-reference.html#usecallback
    */
  @inline final def useCallback6[A, B, C, D, E, F](f: (A, B, C, D, E, F) => Callback)(implicit step: Step): step.Next[Reusable[(A, B, C, D, E, F) => Callback]] =
    useCallback((_: Ctx) => (_: UseCallbackInline)(f))

  /** Returns a memoized callback.
    *
    * Pass an inline callback and dependencies. useCallback will return a memoized version of the callback that only
    * changes if one of the dependencies has changed. This is useful when passing callbacks to optimized child
    * components that rely on reference equality to prevent unnecessary renders.
    *
    * @see https://reactjs.org/docs/hooks-reference.html#usecallback
    */
  @inline final def useCallback6[A, B, C, D, E, F, Z](f: (A, B, C, D, E, F) => Callback, deps: Z)(implicit r: Reusability[Z], step: Step): step.Next[Reusable[(A, B, C, D, E, F) => Callback]] =
    useCallback((_: Ctx) => (_: UseCallbackInline)(f, deps))


  /** Returns a memoized callback.
    *
    * @see https://reactjs.org/docs/hooks-reference.html#usecallback
    */
  @inline final def useCallback7[A, B, C, D, E, F, G](f: (A, B, C, D, E, F, G) => Callback)(implicit step: Step): step.Next[Reusable[(A, B, C, D, E, F, G) => Callback]] =
    useCallback((_: Ctx) => (_: UseCallbackInline)(f))

  /** Returns a memoized callback.
    *
    * Pass an inline callback and dependencies. useCallback will return a memoized version of the callback that only
    * changes if one of the dependencies has changed. This is useful when passing callbacks to optimized child
    * components that rely on reference equality to prevent unnecessary renders.
    *
    * @see https://reactjs.org/docs/hooks-reference.html#usecallback
    */
  @inline final def useCallback7[A, B, C, D, E, F, G, Z](f: (A, B, C, D, E, F, G) => Callback, deps: Z)(implicit r: Reusability[Z], step: Step): step.Next[Reusable[(A, B, C, D, E, F, G) => Callback]] =
    useCallback((_: Ctx) => (_: UseCallbackInline)(f, deps))


  /** Returns a memoized callback.
    *
    * @see https://reactjs.org/docs/hooks-reference.html#usecallback
    */
  @inline final def useCallback8[A, B, C, D, E, F, G, H](f: (A, B, C, D, E, F, G, H) => Callback)(implicit step: Step): step.Next[Reusable[(A, B, C, D, E, F, G, H) => Callback]] =
    useCallback((_: Ctx) => (_: UseCallbackInline)(f))

  /** Returns a memoized callback.
    *
    * Pass an inline callback and dependencies. useCallback will return a memoized version of the callback that only
    * changes if one of the dependencies has changed. This is useful when passing callbacks to optimized child
    * components that rely on reference equality to prevent unnecessary renders.
    *
    * @see https://reactjs.org/docs/hooks-reference.html#usecallback
    */
  @inline final def useCallback8[A, B, C, D, E, F, G, H, Z](f: (A, B, C, D, E, F, G, H) => Callback, deps: Z)(implicit r: Reusability[Z], step: Step): step.Next[Reusable[(A, B, C, D, E, F, G, H) => Callback]] =
    useCallback((_: Ctx) => (_: UseCallbackInline)(f, deps))


  /** Returns a memoized callback.
    *
    * @see https://reactjs.org/docs/hooks-reference.html#usecallback
    */
  @inline final def useCallback9[A, B, C, D, E, F, G, H, I](f: (A, B, C, D, E, F, G, H, I) => Callback)(implicit step: Step): step.Next[Reusable[(A, B, C, D, E, F, G, H, I) => Callback]] =
    useCallback((_: Ctx) => (_: UseCallbackInline)(f))

  /** Returns a memoized callback.
    *
    * Pass an inline callback and dependencies. useCallback will return a memoized version of the callback that only
    * changes if one of the dependencies has changed. This is useful when passing callbacks to optimized child
    * components that rely on reference equality to prevent unnecessary renders.
    *
    * @see https://reactjs.org/docs/hooks-reference.html#usecallback
    */
  @inline final def useCallback9[A, B, C, D, E, F, G, H, I, Z](f: (A, B, C, D, E, F, G, H, I) => Callback, deps: Z)(implicit r: Reusability[Z], step: Step): step.Next[Reusable[(A, B, C, D, E, F, G, H, I) => Callback]] =
    useCallback((_: Ctx) => (_: UseCallbackInline)(f, deps))


  /** Returns a memoized callback.
    *
    * @see https://reactjs.org/docs/hooks-reference.html#usecallback
    */
  @inline final def useCallback10[A, B, C, D, E, F, G, H, I, J](f: (A, B, C, D, E, F, G, H, I, J) => Callback)(implicit step: Step): step.Next[Reusable[(A, B, C, D, E, F, G, H, I, J) => Callback]] =
    useCallback((_: Ctx) => (_: UseCallbackInline)(f))

  /** Returns a memoized callback.
    *
    * Pass an inline callback and dependencies. useCallback will return a memoized version of the callback that only
    * changes if one of the dependencies has changed. This is useful when passing callbacks to optimized child
    * components that rely on reference equality to prevent unnecessary renders.
    *
    * @see https://reactjs.org/docs/hooks-reference.html#usecallback
    */
  @inline final def useCallback10[A, B, C, D, E, F, G, H, I, J, Z](f: (A, B, C, D, E, F, G, H, I, J) => Callback, deps: Z)(implicit r: Reusability[Z], step: Step): step.Next[Reusable[(A, B, C, D, E, F, G, H, I, J) => Callback]] =
    useCallback((_: Ctx) => (_: UseCallbackInline)(f, deps))


  /** Returns a memoized callback.
    *
    * @see https://reactjs.org/docs/hooks-reference.html#usecallback
    */
  @inline final def useCallback11[A, B, C, D, E, F, G, H, I, J, K](f: (A, B, C, D, E, F, G, H, I, J, K) => Callback)(implicit step: Step): step.Next[Reusable[(A, B, C, D, E, F, G, H, I, J, K) => Callback]] =
    useCallback((_: Ctx) => (_: UseCallbackInline)(f))

  /** Returns a memoized callback.
    *
    * Pass an inline callback and dependencies. useCallback will return a memoized version of the callback that only
    * changes if one of the dependencies has changed. This is useful when passing callbacks to optimized child
    * components that rely on reference equality to prevent unnecessary renders.
    *
    * @see https://reactjs.org/docs/hooks-reference.html#usecallback
    */
  @inline final def useCallback11[A, B, C, D, E, F, G, H, I, J, K, Z](f: (A, B, C, D, E, F, G, H, I, J, K) => Callback, deps: Z)(implicit r: Reusability[Z], step: Step): step.Next[Reusable[(A, B, C, D, E, F, G, H, I, J, K) => Callback]] =
    useCallback((_: Ctx) => (_: UseCallbackInline)(f, deps))


  /** Returns a memoized callback.
    *
    * @see https://reactjs.org/docs/hooks-reference.html#usecallback
    */
  @inline final def useCallback12[A, B, C, D, E, F, G, H, I, J, K, L](f: (A, B, C, D, E, F, G, H, I, J, K, L) => Callback)(implicit step: Step): step.Next[Reusable[(A, B, C, D, E, F, G, H, I, J, K, L) => Callback]] =
    useCallback((_: Ctx) => (_: UseCallbackInline)(f))

  /** Returns a memoized callback.
    *
    * Pass an inline callback and dependencies. useCallback will return a memoized version of the callback that only
    * changes if one of the dependencies has changed. This is useful when passing callbacks to optimized child
    * components that rely on reference equality to prevent unnecessary renders.
    *
    * @see https://reactjs.org/docs/hooks-reference.html#usecallback
    */
  @inline final def useCallback12[A, B, C, D, E, F, G, H, I, J, K, L, Z](f: (A, B, C, D, E, F, G, H, I, J, K, L) => Callback, deps: Z)(implicit r: Reusability[Z], step: Step): step.Next[Reusable[(A, B, C, D, E, F, G, H, I, J, K, L) => Callback]] =
    useCallback((_: Ctx) => (_: UseCallbackInline)(f, deps))


  /** Returns a memoized callback.
    *
    * @see https://reactjs.org/docs/hooks-reference.html#usecallback
    */
  @inline final def useCallback13[A, B, C, D, E, F, G, H, I, J, K, L, M](f: (A, B, C, D, E, F, G, H, I, J, K, L, M) => Callback)(implicit step: Step): step.Next[Reusable[(A, B, C, D, E, F, G, H, I, J, K, L, M) => Callback]] =
    useCallback((_: Ctx) => (_: UseCallbackInline)(f))

  /** Returns a memoized callback.
    *
    * Pass an inline callback and dependencies. useCallback will return a memoized version of the callback that only
    * changes if one of the dependencies has changed. This is useful when passing callbacks to optimized child
    * components that rely on reference equality to prevent unnecessary renders.
    *
    * @see https://reactjs.org/docs/hooks-reference.html#usecallback
    */
  @inline final def useCallback13[A, B, C, D, E, F, G, H, I, J, K, L, M, Z](f: (A, B, C, D, E, F, G, H, I, J, K, L, M) => Callback, deps: Z)(implicit r: Reusability[Z], step: Step): step.Next[Reusable[(A, B, C, D, E, F, G, H, I, J, K, L, M) => Callback]] =
    useCallback((_: Ctx) => (_: UseCallbackInline)(f, deps))


  /** Returns a memoized callback.
    *
    * @see https://reactjs.org/docs/hooks-reference.html#usecallback
    */
  @inline final def useCallback14[A, B, C, D, E, F, G, H, I, J, K, L, M, N](f: (A, B, C, D, E, F, G, H, I, J, K, L, M, N) => Callback)(implicit step: Step): step.Next[Reusable[(A, B, C, D, E, F, G, H, I, J, K, L, M, N) => Callback]] =
    useCallback((_: Ctx) => (_: UseCallbackInline)(f))

  /** Returns a memoized callback.
    *
    * Pass an inline callback and dependencies. useCallback will return a memoized version of the callback that only
    * changes if one of the dependencies has changed. This is useful when passing callbacks to optimized child
    * components that rely on reference equality to prevent unnecessary renders.
    *
    * @see https://reactjs.org/docs/hooks-reference.html#usecallback
    */
  @inline final def useCallback14[A, B, C, D, E, F, G, H, I, J, K, L, M, N, Z](f: (A, B, C, D, E, F, G, H, I, J, K, L, M, N) => Callback, deps: Z)(implicit r: Reusability[Z], step: Step): step.Next[Reusable[(A, B, C, D, E, F, G, H, I, J, K, L, M, N) => Callback]] =
    useCallback((_: Ctx) => (_: UseCallbackInline)(f, deps))


  /** Returns a memoized callback.
    *
    * @see https://reactjs.org/docs/hooks-reference.html#usecallback
    */
  @inline final def useCallback15[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O](f: (A, B, C, D, E, F, G, H, I, J, K, L, M, N, O) => Callback)(implicit step: Step): step.Next[Reusable[(A, B, C, D, E, F, G, H, I, J, K, L, M, N, O) => Callback]] =
    useCallback((_: Ctx) => (_: UseCallbackInline)(f))

  /** Returns a memoized callback.
    *
    * Pass an inline callback and dependencies. useCallback will return a memoized version of the callback that only
    * changes if one of the dependencies has changed. This is useful when passing callbacks to optimized child
    * components that rely on reference equality to prevent unnecessary renders.
    *
    * @see https://reactjs.org/docs/hooks-reference.html#usecallback
    */
  @inline final def useCallback15[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, Z](f: (A, B, C, D, E, F, G, H, I, J, K, L, M, N, O) => Callback, deps: Z)(implicit r: Reusability[Z], step: Step): step.Next[Reusable[(A, B, C, D, E, F, G, H, I, J, K, L, M, N, O) => Callback]] =
    useCallback((_: Ctx) => (_: UseCallbackInline)(f, deps))


  /** Returns a memoized callback.
    *
    * @see https://reactjs.org/docs/hooks-reference.html#usecallback
    */
  @inline final def useCallback16[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P](f: (A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P) => Callback)(implicit step: Step): step.Next[Reusable[(A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P) => Callback]] =
    useCallback((_: Ctx) => (_: UseCallbackInline)(f))

  /** Returns a memoized callback.
    *
    * Pass an inline callback and dependencies. useCallback will return a memoized version of the callback that only
    * changes if one of the dependencies has changed. This is useful when passing callbacks to optimized child
    * components that rely on reference equality to prevent unnecessary renders.
    *
    * @see https://reactjs.org/docs/hooks-reference.html#usecallback
    */
  @inline final def useCallback16[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Z](f: (A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P) => Callback, deps: Z)(implicit r: Reusability[Z], step: Step): step.Next[Reusable[(A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P) => Callback]] =
    useCallback((_: Ctx) => (_: UseCallbackInline)(f, deps))


  /** Returns a memoized callback.
    *
    * @see https://reactjs.org/docs/hooks-reference.html#usecallback
    */
  @inline final def useCallback17[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q](f: (A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q) => Callback)(implicit step: Step): step.Next[Reusable[(A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q) => Callback]] =
    useCallback((_: Ctx) => (_: UseCallbackInline)(f))

  /** Returns a memoized callback.
    *
    * Pass an inline callback and dependencies. useCallback will return a memoized version of the callback that only
    * changes if one of the dependencies has changed. This is useful when passing callbacks to optimized child
    * components that rely on reference equality to prevent unnecessary renders.
    *
    * @see https://reactjs.org/docs/hooks-reference.html#usecallback
    */
  @inline final def useCallback17[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, Z](f: (A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q) => Callback, deps: Z)(implicit r: Reusability[Z], step: Step): step.Next[Reusable[(A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q) => Callback]] =
    useCallback((_: Ctx) => (_: UseCallbackInline)(f, deps))


  /** Returns a memoized callback.
    *
    * @see https://reactjs.org/docs/hooks-reference.html#usecallback
    */
  @inline final def useCallback18[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R](f: (A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R) => Callback)(implicit step: Step): step.Next[Reusable[(A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R) => Callback]] =
    useCallback((_: Ctx) => (_: UseCallbackInline)(f))

  /** Returns a memoized callback.
    *
    * Pass an inline callback and dependencies. useCallback will return a memoized version of the callback that only
    * changes if one of the dependencies has changed. This is useful when passing callbacks to optimized child
    * components that rely on reference equality to prevent unnecessary renders.
    *
    * @see https://reactjs.org/docs/hooks-reference.html#usecallback
    */
  @inline final def useCallback18[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, Z](f: (A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R) => Callback, deps: Z)(implicit r: Reusability[Z], step: Step): step.Next[Reusable[(A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R) => Callback]] =
    useCallback((_: Ctx) => (_: UseCallbackInline)(f, deps))


  /** Returns a memoized callback.
    *
    * @see https://reactjs.org/docs/hooks-reference.html#usecallback
    */
  @inline final def useCallback19[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S](f: (A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S) => Callback)(implicit step: Step): step.Next[Reusable[(A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S) => Callback]] =
    useCallback((_: Ctx) => (_: UseCallbackInline)(f))

  /** Returns a memoized callback.
    *
    * Pass an inline callback and dependencies. useCallback will return a memoized version of the callback that only
    * changes if one of the dependencies has changed. This is useful when passing callbacks to optimized child
    * components that rely on reference equality to prevent unnecessary renders.
    *
    * @see https://reactjs.org/docs/hooks-reference.html#usecallback
    */
  @inline final def useCallback19[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, Z](f: (A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S) => Callback, deps: Z)(implicit r: Reusability[Z], step: Step): step.Next[Reusable[(A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S) => Callback]] =
    useCallback((_: Ctx) => (_: UseCallbackInline)(f, deps))


  /** Returns a memoized callback.
    *
    * @see https://reactjs.org/docs/hooks-reference.html#usecallback
    */
  @inline final def useCallback20[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T](f: (A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T) => Callback)(implicit step: Step): step.Next[Reusable[(A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T) => Callback]] =
    useCallback((_: Ctx) => (_: UseCallbackInline)(f))

  /** Returns a memoized callback.
    *
    * Pass an inline callback and dependencies. useCallback will return a memoized version of the callback that only
    * changes if one of the dependencies has changed. This is useful when passing callbacks to optimized child
    * components that rely on reference equality to prevent unnecessary renders.
    *
    * @see https://reactjs.org/docs/hooks-reference.html#usecallback
    */
  @inline final def useCallback20[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, Z](f: (A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T) => Callback, deps: Z)(implicit r: Reusability[Z], step: Step): step.Next[Reusable[(A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T) => Callback]] =
    useCallback((_: Ctx) => (_: UseCallbackInline)(f, deps))


  /** Returns a memoized callback.
    *
    * @see https://reactjs.org/docs/hooks-reference.html#usecallback
    */
  @inline final def useCallback21[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U](f: (A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U) => Callback)(implicit step: Step): step.Next[Reusable[(A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U) => Callback]] =
    useCallback((_: Ctx) => (_: UseCallbackInline)(f))

  /** Returns a memoized callback.
    *
    * Pass an inline callback and dependencies. useCallback will return a memoized version of the callback that only
    * changes if one of the dependencies has changed. This is useful when passing callbacks to optimized child
    * components that rely on reference equality to prevent unnecessary renders.
    *
    * @see https://reactjs.org/docs/hooks-reference.html#usecallback
    */
  @inline final def useCallback21[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Z](f: (A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U) => Callback, deps: Z)(implicit r: Reusability[Z], step: Step): step.Next[Reusable[(A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U) => Callback]] =
    useCallback((_: Ctx) => (_: UseCallbackInline)(f, deps))


  /** Returns a memoized callback.
    *
    * @see https://reactjs.org/docs/hooks-reference.html#usecallback
    */
  @inline final def useCallback22[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V](f: (A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V) => Callback)(implicit step: Step): step.Next[Reusable[(A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V) => Callback]] =
    useCallback((_: Ctx) => (_: UseCallbackInline)(f))

  /** Returns a memoized callback.
    *
    * Pass an inline callback and dependencies. useCallback will return a memoized version of the callback that only
    * changes if one of the dependencies has changed. This is useful when passing callbacks to optimized child
    * components that rely on reference equality to prevent unnecessary renders.
    *
    * @see https://reactjs.org/docs/hooks-reference.html#usecallback
    */
  @inline final def useCallback22[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, Z](f: (A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V) => Callback, deps: Z)(implicit r: Reusability[Z], step: Step): step.Next[Reusable[(A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V) => Callback]] =
    useCallback((_: Ctx) => (_: UseCallbackInline)(f, deps))

}

// =====================================================================================================================

trait UseCallbackArgInstances {

  implicit def c1[A]: UseCallbackArg[(A) => Callback] =
    UseCallbackArg[(A) => Callback, js.Function1[A, Unit]](
      f => f(_).runNow())(
      z => Reusable.byRef(z).withValue((a) => Callback(z(a))))


  implicit def c2[A, B]: UseCallbackArg[(A, B) => Callback] =
    UseCallbackArg[(A, B) => Callback, js.Function2[A, B, Unit]](
      f => f(_, _).runNow())(
      z => Reusable.byRef(z).withValue((a, b) => Callback(z(a, b))))


  implicit def c3[A, B, C]: UseCallbackArg[(A, B, C) => Callback] =
    UseCallbackArg[(A, B, C) => Callback, js.Function3[A, B, C, Unit]](
      f => f(_, _, _).runNow())(
      z => Reusable.byRef(z).withValue((a, b, c) => Callback(z(a, b, c))))


  implicit def c4[A, B, C, D]: UseCallbackArg[(A, B, C, D) => Callback] =
    UseCallbackArg[(A, B, C, D) => Callback, js.Function4[A, B, C, D, Unit]](
      f => f(_, _, _, _).runNow())(
      z => Reusable.byRef(z).withValue((a, b, c, d) => Callback(z(a, b, c, d))))


  implicit def c5[A, B, C, D, E]: UseCallbackArg[(A, B, C, D, E) => Callback] =
    UseCallbackArg[(A, B, C, D, E) => Callback, js.Function5[A, B, C, D, E, Unit]](
      f => f(_, _, _, _, _).runNow())(
      z => Reusable.byRef(z).withValue((a, b, c, d, e) => Callback(z(a, b, c, d, e))))


  implicit def c6[A, B, C, D, E, F]: UseCallbackArg[(A, B, C, D, E, F) => Callback] =
    UseCallbackArg[(A, B, C, D, E, F) => Callback, js.Function6[A, B, C, D, E, F, Unit]](
      f => f(_, _, _, _, _, _).runNow())(
      z => Reusable.byRef(z).withValue((a, b, c, d, e, f) => Callback(z(a, b, c, d, e, f))))


  implicit def c7[A, B, C, D, E, F, G]: UseCallbackArg[(A, B, C, D, E, F, G) => Callback] =
    UseCallbackArg[(A, B, C, D, E, F, G) => Callback, js.Function7[A, B, C, D, E, F, G, Unit]](
      f => f(_, _, _, _, _, _, _).runNow())(
      z => Reusable.byRef(z).withValue((a, b, c, d, e, f, g) => Callback(z(a, b, c, d, e, f, g))))


  implicit def c8[A, B, C, D, E, F, G, H]: UseCallbackArg[(A, B, C, D, E, F, G, H) => Callback] =
    UseCallbackArg[(A, B, C, D, E, F, G, H) => Callback, js.Function8[A, B, C, D, E, F, G, H, Unit]](
      f => f(_, _, _, _, _, _, _, _).runNow())(
      z => Reusable.byRef(z).withValue((a, b, c, d, e, f, g, h) => Callback(z(a, b, c, d, e, f, g, h))))


  implicit def c9[A, B, C, D, E, F, G, H, I]: UseCallbackArg[(A, B, C, D, E, F, G, H, I) => Callback] =
    UseCallbackArg[(A, B, C, D, E, F, G, H, I) => Callback, js.Function9[A, B, C, D, E, F, G, H, I, Unit]](
      f => f(_, _, _, _, _, _, _, _, _).runNow())(
      z => Reusable.byRef(z).withValue((a, b, c, d, e, f, g, h, i) => Callback(z(a, b, c, d, e, f, g, h, i))))


  implicit def c10[A, B, C, D, E, F, G, H, I, J]: UseCallbackArg[(A, B, C, D, E, F, G, H, I, J) => Callback] =
    UseCallbackArg[(A, B, C, D, E, F, G, H, I, J) => Callback, js.Function10[A, B, C, D, E, F, G, H, I, J, Unit]](
      f => f(_, _, _, _, _, _, _, _, _, _).runNow())(
      z => Reusable.byRef(z).withValue((a, b, c, d, e, f, g, h, i, j) => Callback(z(a, b, c, d, e, f, g, h, i, j))))


  implicit def c11[A, B, C, D, E, F, G, H, I, J, K]: UseCallbackArg[(A, B, C, D, E, F, G, H, I, J, K) => Callback] =
    UseCallbackArg[(A, B, C, D, E, F, G, H, I, J, K) => Callback, js.Function11[A, B, C, D, E, F, G, H, I, J, K, Unit]](
      f => f(_, _, _, _, _, _, _, _, _, _, _).runNow())(
      z => Reusable.byRef(z).withValue((a, b, c, d, e, f, g, h, i, j, k) => Callback(z(a, b, c, d, e, f, g, h, i, j, k))))


  implicit def c12[A, B, C, D, E, F, G, H, I, J, K, L]: UseCallbackArg[(A, B, C, D, E, F, G, H, I, J, K, L) => Callback] =
    UseCallbackArg[(A, B, C, D, E, F, G, H, I, J, K, L) => Callback, js.Function12[A, B, C, D, E, F, G, H, I, J, K, L, Unit]](
      f => f(_, _, _, _, _, _, _, _, _, _, _, _).runNow())(
      z => Reusable.byRef(z).withValue((a, b, c, d, e, f, g, h, i, j, k, l) => Callback(z(a, b, c, d, e, f, g, h, i, j, k, l))))


  implicit def c13[A, B, C, D, E, F, G, H, I, J, K, L, M]: UseCallbackArg[(A, B, C, D, E, F, G, H, I, J, K, L, M) => Callback] =
    UseCallbackArg[(A, B, C, D, E, F, G, H, I, J, K, L, M) => Callback, js.Function13[A, B, C, D, E, F, G, H, I, J, K, L, M, Unit]](
      f => f(_, _, _, _, _, _, _, _, _, _, _, _, _).runNow())(
      z => Reusable.byRef(z).withValue((a, b, c, d, e, f, g, h, i, j, k, l, m) => Callback(z(a, b, c, d, e, f, g, h, i, j, k, l, m))))


  implicit def c14[A, B, C, D, E, F, G, H, I, J, K, L, M, N]: UseCallbackArg[(A, B, C, D, E, F, G, H, I, J, K, L, M, N) => Callback] =
    UseCallbackArg[(A, B, C, D, E, F, G, H, I, J, K, L, M, N) => Callback, js.Function14[A, B, C, D, E, F, G, H, I, J, K, L, M, N, Unit]](
      f => f(_, _, _, _, _, _, _, _, _, _, _, _, _, _).runNow())(
      z => Reusable.byRef(z).withValue((a, b, c, d, e, f, g, h, i, j, k, l, m, n) => Callback(z(a, b, c, d, e, f, g, h, i, j, k, l, m, n))))


  implicit def c15[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O]: UseCallbackArg[(A, B, C, D, E, F, G, H, I, J, K, L, M, N, O) => Callback] =
    UseCallbackArg[(A, B, C, D, E, F, G, H, I, J, K, L, M, N, O) => Callback, js.Function15[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, Unit]](
      f => f(_, _, _, _, _, _, _, _, _, _, _, _, _, _, _).runNow())(
      z => Reusable.byRef(z).withValue((a, b, c, d, e, f, g, h, i, j, k, l, m, n, o) => Callback(z(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o))))


  implicit def c16[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P]: UseCallbackArg[(A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P) => Callback] =
    UseCallbackArg[(A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P) => Callback, js.Function16[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Unit]](
      f => f(_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _).runNow())(
      z => Reusable.byRef(z).withValue((a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p) => Callback(z(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p))))


  implicit def c17[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q]: UseCallbackArg[(A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q) => Callback] =
    UseCallbackArg[(A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q) => Callback, js.Function17[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, Unit]](
      f => f(_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _).runNow())(
      z => Reusable.byRef(z).withValue((a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q) => Callback(z(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q))))


  implicit def c18[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R]: UseCallbackArg[(A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R) => Callback] =
    UseCallbackArg[(A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R) => Callback, js.Function18[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, Unit]](
      f => f(_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _).runNow())(
      z => Reusable.byRef(z).withValue((a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r) => Callback(z(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r))))


  implicit def c19[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S]: UseCallbackArg[(A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S) => Callback] =
    UseCallbackArg[(A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S) => Callback, js.Function19[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, Unit]](
      f => f(_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _).runNow())(
      z => Reusable.byRef(z).withValue((a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s) => Callback(z(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s))))


  implicit def c20[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T]: UseCallbackArg[(A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T) => Callback] =
    UseCallbackArg[(A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T) => Callback, js.Function20[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, Unit]](
      f => f(_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _).runNow())(
      z => Reusable.byRef(z).withValue((a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t) => Callback(z(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t))))


  implicit def c21[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U]: UseCallbackArg[(A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U) => Callback] =
    UseCallbackArg[(A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U) => Callback, js.Function21[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Unit]](
      f => f(_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _).runNow())(
      z => Reusable.byRef(z).withValue((a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u) => Callback(z(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u))))


  implicit def c22[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V]: UseCallbackArg[(A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V) => Callback] =
    UseCallbackArg[(A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V) => Callback, js.Function22[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, Unit]](
      f => f(_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _).runNow())(
      z => Reusable.byRef(z).withValue((a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v) => Callback(z(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v))))

}
